       Real  Save_Lat(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Lon(iswath_B/ILINE,Tot_scan_B)
       Real  Save_SolZen(iswath_B/ILINE,Tot_scan_B)
       Real  Save_View_angle(iswath_B/ILINE,Tot_scan_B)
       Real  Save_View_phi(iswath_B/ILINE,Tot_scan_B)
       Real  Save_solar_phi(iswath_B/ILINE,Tot_scan_B) 
       Real  Save_Scatt_angle(iswath_B/ILINE,Tot_scan_B) 
       Real  Save_Glint_angle(iswath_B/ILINE,Tot_scan_B)  
       Real  Save_Sea_Land_Flag(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Cld_mask_500(iswath_B,Iline*Tot_scan_B)
       Real  Save_cloud_distance_500(iswath_B,Iline*Tot_scan_B)
       Real  Save_land_ocean_Quality(iswath_B/ILINE,Tot_scan_B)
       Real  Save_land_ocean_tau(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Image_land_ocean_tau(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Aerosol_Type(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Fitting_Error_Land(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Surface_Reflectance_Land(iswath_B/ILINE,Tot_scan_B,Land_Sol3)
       Real  Save_corrected(iswath_B/ILINE,Tot_scan_B,Land_Sol4)
       Real  Save_dust_weighting(iswath_B/ILINE,Tot_scan_B)
       Real  Save_NUMPIXELS_land(iswath_B/ILINE,Tot_scan_B,Land_Sol3) 
       Real  Save_ref_Land(iswath_B/ILINE,Tot_scan_B,Land_Sol3)
       Real  Save_SDS_Land(iswath_B/ILINE,Tot_scan_B,Land_Sol3) 
       Real  Save_SDS_mass_conc_land(iswath_B/ILINE,Tot_scan_B)
       Real Save_CLDFRC_land(iswath_B/ILINE,Tot_scan_B)
       Real Save_average_Tau_Ocean(iswath_B/ILINE,Tot_scan_B,NWAVN)
       Real Save_SDSTAUS_average(iswath_B/ILINE,Tot_scan_B,NWAVN)
       Real Save_SDSTAUL_average(iswath_B/ILINE,Tot_scan_B,NWAVN)
       Real Save_SDS_mass_conc_ocean(iswath_B/ILINE,Tot_scan_B) 
       Real Save_CLDFRC_Ocean(iswath_B/ILINE,Tot_scan_B)
       Real Save_effrad(iswath_B/ILINE,Tot_scan_B) 
       Real Save_PSML003_Ocean(iswath_B/ILINE,Tot_scan_B)
       Real Save_ASSY(iswath_B/ILINE,Tot_scan_B,NWAVN)
       Real Save_BACK(iswath_B/ILINE,Tot_scan_B,NWAVN) 
       Real Save_SDS_angs_coeff1(iswath_B/ILINE,Tot_scan_B) 
       Real Save_SDS_angs_coeff2(iswath_B/ILINE,Tot_scan_B)
       Real Save_Least_error(iswath_B/ILINE,Tot_scan_B) 
       Real Save_small_weighting(iswath_B/ILINE,Tot_scan_B)
       Real Save_SDS_AOT_model(iswath_B/ILINE,Tot_scan_B,num_model_index)
       Real Save_NUMPIXELS_Ocean(iswath_B/ILINE,Tot_scan_B,NWAVN) 
       Real Save_ref_Ocean(iswath_B/ILINE,Tot_scan_B,NWAVN) 
       Real Save_STD_Ocean(iswath_B/ILINE,Tot_scan_B,NWAVN)
       Real Save_Wspeed_Ocean(iswath_B/ILINE,Tot_scan_B)
       Real Save_Topo_Height(iswath_B/ILINE,Tot_scan_B)
       Real Save_land_ocean_Q_Ret(iswath_B/ILINE,Tot_scan_B,Land_Sol1) 
       Real Save_ave_clddis_land_ocean(iswath_B/ILINE,Tot_scan_B) 
       Real Save_Dust_Flag_ocean(iswath_B/ILINE,Tot_scan_B) 
       Real save_ref_Land_PACE(iswath_B/ILINE,Tot_scan_B,9)
       Real Save_smw_land(iswath_B/ILINE,Tot_scan_B)
       
       
        
       
      
        
      
       
     
       
      
      
      
     
      