       Real  Save_Lat_UV(iswath_B/ILINE,Tot_scan_B)
       Real  Save_Lon_UV(iswath_B/ILINE,Tot_scan_B)
       Real  Save_SolZen_UV(iswath_B/ILINE,Tot_scan_B)
       Real  Save_View_angle_UV(iswath_B/ILINE,Tot_scan_B)
       Real  Save_View_phi_UV(iswath_B/ILINE,Tot_scan_B)
       Real  Save_solar_phi_UV(iswath_B/ILINE,Tot_scan_B) 
       Real Save_average_Tau_Ocean_UV(iswath_B/ILINE,Tot_scan_B,NWAV_uv+7)
       Real Save_average_Omega_Ocean_UV(iswath_B/ILINE,Tot_scan_B,NWAV_uv+1)
       Real Save_mode_F_FUV(iswath_B/ILINE,Tot_scan_B)
       Real Save_mode_C_FUV(iswath_B/ILINE,Tot_scan_B)
       Real Save_Small_weighting_FUV(iswath_B/ILINE,Tot_scan_B)
       Real Save_Index_Albedo(iswath_B/ILINE,Tot_scan_B)
       Real Save_Index_Height(iswath_B/ILINE,Tot_scan_B)
       Real Save_Fitting_Error(iswath_B/ILINE,Tot_scan_B)
       Real Save_ref_allwav_uv(iswath_B/ILINE,Tot_scan_B,NWAV_uv+7) 
       REAL Save_ref_allwav_PACE(iswath_B/ILINE,Tot_scan_B,NWAV_uv+3) 
       REAL Save_average_Tau_PACE(iswath_B/ILINE,Tot_scan_B,NWAV_uv+3) 
       
       
      
      
      
     
      