
      real nvalx412
      real nvalx
      real theta0, theta, phi, sfc_ref412, tau, w0, w0_470
      real nvalx650, sfc_ref650
      real sfc_ref470
      real nvalx470

      real sfcprs

      common /aottbl/ nvalx412(12,46,30,10,8,20), nvalx(12,46,30,10), 
     * theta0(12), theta(46), 
     * phi(30), sfc_ref412(20), tau(10), w0(8), w0_470(4),
     * nvalx650(12,46,30,10,24), sfc_ref650(24), sfc_ref470(24), 
     * sfcprs(360,720),
     * nvalx470(12,46,30,10,4,24) 

